curl --request DELETE  \
  --url http://localhost:5263/catalog/3 \
  --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImpuY2RiZDZYRzhrZHJJUlZEdXNveiJ9.eyJpc3MiOiJodHRwczovL2Rldi00enpzY2s3cW94cWEyYnRxLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiI4MmNaSjMwM2RqWURKQWczNk9ydXZLZXVEaE5jQkIxcUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9EZXNlcnREZWVyUHJvamVjdCIsImlhdCI6MTc0MzgwNTcxMSwiZXhwIjoxNzQzODkyMTExLCJzY29wZSI6ImRlbGV0ZTpjYXRhbG9nIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoiODJjWkozMDNkallESkFnMzZPcnV2S2V1RGhOY0JCMXEifQ.nkCFXGRfVgmvAmqqOboDBrKuPRcElUy14gGKLrnxr9LhLFF_aioHyrDB_v4nW_oRUYBeO5ZfWop0iTBlMOg_Q346PlGXqS78ieu8l7ByuE4igJhccmbQGWsPDgaauUpgqSVYVCVwbAXMxK59R7Neo9tjLeGVNImGeSd27-XfF8juyb4ZvS9lFIx6r3KkLfzQJDRNxKo_gqvqQEC5fxDBMDQ9C6A-3HNJXfYJWB2Cc1QzUEcNU2QJ4UvpF0evnuupc7pTHz5ymzNX4_SGTfSN_GfkPcuNuKRQy6Srv17XEZPpC_Jxov4ydFKNMPieks2y4lHFuMWpDbwVnBx4hUXjow'